ToDoList/ToDoList/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ToDoList.Data;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using ToDoList.Models;
using ToDoList.ViewModels;

namespace ToDoList.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ItemController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            Itemrepository ItemrepositoryNew = new Itemrepository(_db);
            return View(ItemrepositoryNew.GetItems());
        }

        //GET-create
        public IActionResult Create()
        {
            IEnumerable<User> userview = _db.Users;
            List<string> userlist = new List<string> { };

            foreach (var username in userview)
            {
                userlist.Add(username.Username);
            }
            ViewBag.Users = new SelectList(userlist);
            return View();
        }


        [HttpGet] //[View Completed Tasks] Get
        public IActionResult ViewHistory(GroupAndItemModel model)
        {
            int groupId = model.Groups[0].Id;

            List<CompletedTask> completedItems = _db.CompletedTasks.Where(t => t.GroupId == groupId).ToList();
            List<Group> thisGroup = _db.Groups.Where(g => g.Id == groupId).ToList();

            CompletedTaskViewModel viewModel = new CompletedTaskViewModel()
            {
                Groups = thisGroup,
                Items = completedItems
            };

            return View(viewModel);
        }

        [HttpPost] // [Create Item in Group] Post
        public IActionResult CreateGroupItem(GroupAndItemModel group)
        {
            int groupId = group.Groups[0].Id;
            List<string> groupUserEmail = new List<string> { };
            List<string> userList = new List<string> { };

            List<MemberAccess> memberAccess = _db.Accesses.Where(u => u.GroupId == groupId).ToList();

            foreach (var user in memberAccess)
            {
                    groupUserEmail.Add(user.Email);
            }
            foreach (var email in groupUserEmail)
            {
                List<User> users = _db.Users.Where(u => u.Email == email).ToList();
                userList.Add(users[0].Username);
            }

            Item viewItem = new Item();
            viewItem.DeadlineDate = DateTime.Today.AddDays(2);
            viewItem.GroupId = groupId;

            ViewBag.Users = new SelectList(userList);

            return View(viewItem);
        }

        [HttpPost]
        public ActionResult Drop(FormCollection form)
        {
            var optionsValue = form["Options"];
            return RedirectToAction("Drop");
        }

        //Post-Create method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            IEnumerable<User> objList = _db.Users;
            if(obj.DeadlineDate < DateTime.Now)
            {
                return RedirectToAction("ErrorDate");
            }

            obj.UserId = (from user in objList
                          where obj.ResponsibleUser == user.Username
                          select user.Id).FirstOrDefault();

            _db.Items.Add(obj);
            _db.SaveChanges();

            int groupId = obj.GroupId;

            return RedirectToAction("ViewGroup", "Group", new { id = groupId });
        }

        // GET Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Items.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            

            return View(obj);
        }

        //POST Delete
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Items.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            int groupId = obj.GroupId;

            var completedTask = new CompletedTask()
            {
                ItemName = obj.ItemName,
                ItemDescription = obj.ItemDescription,
                ResponsibleUser = obj.ResponsibleUser,
                GroupId = obj.GroupId,
                DeadlineDate = obj.DeadlineDate,
                Finished = DateTime.Now
            };
            _db.CompletedTasks.Add(completedTask);
            _db.Items.Remove(obj);
            _db.SaveChanges();

            if (!string.IsNullOrEmpty(groupId.ToString()))
            {
                return RedirectToAction("ViewGroup", "Group", new { id = groupId });
            }
            return RedirectToAction("Index");
        }

        // GET Edit
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Items.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            IEnumerable<User> userview = _db.Users;
            List<string> userlist = new List<string> { };

            foreach (var username in userview)
            {
                userlist.Add(username.Username);
            }
            ViewBag.Users = new SelectList(userlist);
            return View(obj);
        }

        //Post-Create method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Item obj)
        {
            IEnumerable<User> objList = _db.Users;
            if (obj.DeadlineDate < DateTime.Now)
            {
                return RedirectToAction("ErrorDate");
            }
            obj.UserId = (from user in objList
                          where obj.ResponsibleUser == user.Username
                          select user.Id).FirstOrDefault();
            _db.Items.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult ErrorDate()
        {
            return View();
        }
    }
}

ToDoList/ToDoList/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
@{
    var identity = ClaimTypes.Name;
}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] TASKer </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/icons/check3.png" class="p-3" />TASKer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @*                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">To-Do-List</a>
                            </li>*@
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Sign up</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="GroupListView">Your groups</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="Index">Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Secured">My Account</a>
                            </li>

                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link text-dark text-right" asp-area="" asp-controller="Home" asp-action="Logout"><p class="text-right navbar-nav flex-grow-1">Logout (<span class="text-success">@User.Identity.Name</span>) </p></a>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>